# Funding links for Stemly
# These are displayed as "Sponsor" button on the GitHub repo

# GitHub Sponsors username (uncomment when set up)
# github: [Dakshin10]

# Buy Me a Coffee (uncomment when set up)
# buy_me_a_coffee: stemly

# Open Collective (uncomment when set up)
# open_collective: stemly

# Custom sponsorship URL
custom: ["https://github.com/Dakshin10/Stemly"]
