# Funding links for Stemly
# These are displayed as "Sponsor" button on the GitHub repo

# GitHub Sponsors username
# github: [username]

# Patreon username
# patreon: username

# Open Collective username
# open_collective: username

# Ko-fi username
# ko_fi: username

# Tidelift platform-name/package-name e.g., npm/babel
# tidelift: platform/package

# Community Bridge project-name e.g., cloud-foundry
# community_bridge: project-name

# Liberapay username
# liberapay: username

# IssueHunt username
# issuehunt: username

# Otechie username
# otechie: username

# Custom sponsorship URLs (e.g., PayPal, Buy Me A Coffee, private server)
# custom: ["https://example.com/sponsor"]
